### ISSUE TITLE
Confirming destination of GitHub link in navbar

### ISSUE THREAD

**Issue by wbnns** [NanoSat-MO-Framework/nanosat-mo-framework.github.io#23]
In the navbar, the destination of the `GitHub` link is:
https://github.com/esa/nanosat-mo-framework/tree/master

That particular branch hasn't been updated since November 2019, whereas the `dev` branch is much more up to date (e.g. updated just 4 days ago at the time of this issue).

So just wanted to double-check to make sure linking to the `master` branch was intended (or if it should be a consideration of whether or not to link to the more up to date `dev` branch).

**Comment by CesarCoelho** [comment]
Yes, that's correct, it should be pointing to the master branch.
As you correctly pointed out, the master branch has not been updated for a while. The NMF project was on "maintenance mode" in 2019/2020, so the focus was mostly on fixing bugs to get it fully operational for OPS-SAT.
This situation will change in 2021, as there will be a lot of incoming manpower to work on the NMF.
So we should expect a functional release to be merged into the master branch in 2021 and plenty of new features.

**Comment by wbnns** [comment]
Ah, ok, awesome! If there's ever another opportunity to be a part of the team, I would be super-interested. :pray: 

Closing this issue, then. Cheers.
