### ISSUE TITLE
Migrating source files to esa/nanosat-mo-framework

### ISSUE THREAD

**Issue by wbnns** [NanoSat-MO-Framework/nanosat-mo-framework.github.io#7]
It is technically possible to add the contents of this repository to a `web` folder in the [main NMF repo](https://github.com/esa/nanosat-mo-framework), and serve the website out of it via GitHub pages.

Benefit would be that there would then be a monorepo for all things related to NMF, and might make it easier for other contributors to add to / extend the website as more apps, missions, interfaces etc. become available to help ensure all content is up to date.

**Comment by CesarCoelho** [comment]
I would rather keep it separate for now.
Thanks for the tip!

**Comment by wbnns** [comment]
Ok, cool.
